// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(PagoContext))]
    [Migration("20210425030550_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entidad.Pago", b =>
                {
                    b.Property<string>("PagoId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TerceroId")
                        .HasColumnType("varchar(767)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("PagoId");

                    b.HasIndex("TerceroId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Entidad.Tercero", b =>
                {
                    b.Property<string>("TerceroId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("TerceroId");

                    b.ToTable("Terceros");
                });

            modelBuilder.Entity("Entidad.Pago", b =>
                {
                    b.HasOne("Entidad.Tercero", "Tercero")
                        .WithMany("Pagos")
                        .HasForeignKey("TerceroId");
                });
#pragma warning restore 612, 618
        }
    }
}
